"""
Module C — Camera Calibration / Intrinsics
============================================
Minimal monocular-camera calibration used by the distance & TTC estimator.

Two pieces of geometry are needed to convert pixel coordinates into
metres on a flat road:

    1. focal length in pixels (fx, fy)
        fx = (W / 2) / tan(HFOV / 2)
        We assume square pixels, so fy = fx.

    2. ground-plane mapping
        For a camera at height ``h`` above the ground, level pitch, the
        horizon sits at row ``y_horizon = horizon_y_frac * H``.
        A point on the ground that projects to row ``y_bot`` has metric
        forward distance:

            Z = fy * h / (y_bot - y_horizon)            (y_bot below horizon)

Defaults are sane for a typical 1080p dashcam:

    * HFOV = 75° (mid-range; action cams hit 120°+, narrow dashcams ~55°)
    * mount height = 1.4 m (sedan dashboard)
    * horizon row = 0.50 * frame_height (level mount, flat road)

Override per-vehicle from main.py CLI: --cam-hfov, --cam-height, --cam-horizon.

Custom calibration
------------------
If ``calibration.npz`` exists (generated by ``calibration_tool.py``),
the pipeline will use the **real** fx/fy from checkerboard calibration
instead of estimating from HFOV. Frames are also undistorted before
being fed to the detection models.

Why this matters
----------------
Module C currently classifies "front vehicle proximity" by **box area
ratio** alone — a class-agnostic proxy that misclassifies large
trucks (huge boxes, far away) as VERY_CLOSE and motorcycles as NONE.
Real distance bands fix that, and once we have distance per track we
can also derive a closing-rate-based TTC.
"""

from __future__ import annotations

import math
import os
from dataclasses import dataclass, field
from typing import Optional

import cv2
import numpy as np


@dataclass
class CameraIntrinsics:
    """Single-camera pinhole calibration, level mount, flat-road assumption."""

    frame_w: int
    frame_h: int

    # Horizontal field of view in degrees. Vertical FOV is derived assuming
    # square pixels.
    hfov_deg: float = 75.0

    # Camera mount height above ground in metres.
    h_camera: float = 1.4

    # Row index (as fraction of frame height) that maps to the horizon line
    # — i.e. infinite ground distance. 0.50 ⇒ horizon at frame mid-line.
    horizon_y_frac: float = 0.50

    # Optional: nudge for real cars whose grille is slightly forward of the
    # bbox foot point. Adds N metres to every pinhole reading.
    distance_offset_m: float = 0.0

    # ── Custom calibration overrides (set by load_from_calibration_file) ──
    _fx_override: Optional[float] = field(default=None, repr=False)
    _fy_override: Optional[float] = field(default=None, repr=False)
    _cam_matrix: Optional[np.ndarray] = field(default=None, repr=False)
    _dist_coeff: Optional[np.ndarray] = field(default=None, repr=False)
    _undistort_map1: Optional[np.ndarray] = field(default=None, repr=False)
    _undistort_map2: Optional[np.ndarray] = field(default=None, repr=False)
    _calibrated: bool = field(default=False, repr=False)

    # ── Derived properties ──────────────────────────────────────────────────
    @property
    def fx(self) -> float:
        """Focal length in pixels along the x-axis."""
        if self._fx_override is not None:
            return self._fx_override
        return (self.frame_w * 0.5) / math.tan(math.radians(self.hfov_deg) * 0.5)

    @property
    def fy(self) -> float:
        """Focal length in pixels along the y-axis (= fx, square pixels)."""
        if self._fy_override is not None:
            return self._fy_override
        return self.fx

    @property
    def horizon_y(self) -> float:
        """Pixel row of the horizon."""
        return self.horizon_y_frac * self.frame_h

    @property
    def is_calibrated(self) -> bool:
        """True if using real calibration data (not HFOV estimates)."""
        return self._calibrated

    # ── Convenience constructor ─────────────────────────────────────────────
    @classmethod
    def default_for(cls, frame_w: int, frame_h: int) -> "CameraIntrinsics":
        return cls(frame_w=frame_w, frame_h=frame_h)

    # ── Load from calibration file ──────────────────────────────────────────
    @classmethod
    def from_calibration_file(
        cls,
        calib_path: str,
        frame_w: int,
        frame_h: int,
        h_camera: float = 1.4,
        horizon_y_frac: float = 0.50,
    ) -> "CameraIntrinsics":
        """
        Tạo CameraIntrinsics từ file calibration.npz.
        Sử dụng fx, fy thật từ checkerboard calibration thay vì ước tính.
        Chuẩn bị undistort maps để sửa méo frame.
        """
        data = np.load(calib_path, allow_pickle=True)
        cam_matrix = data["cam_matrix"]
        dist_coeff = data["dist_coeff"]
        reproj_error = float(data["reproj_error"])

        fx_real = cam_matrix[0, 0]
        fy_real = cam_matrix[1, 1]

        # Tính HFOV thật từ fx
        hfov_real = 2 * math.degrees(math.atan(frame_w / (2 * fx_real)))

        # Tính optimal camera matrix và undistort maps
        new_cam_matrix, roi = cv2.getOptimalNewCameraMatrix(
            cam_matrix, dist_coeff, (frame_w, frame_h), 1, (frame_w, frame_h)
        )
        map1, map2 = cv2.initUndistortRectifyMap(
            cam_matrix, dist_coeff, None, new_cam_matrix,
            (frame_w, frame_h), cv2.CV_16SC2
        )

        instance = cls(
            frame_w=frame_w,
            frame_h=frame_h,
            hfov_deg=hfov_real,
            h_camera=h_camera,
            horizon_y_frac=horizon_y_frac,
        )
        instance._fx_override = fx_real
        instance._fy_override = fy_real
        instance._cam_matrix = cam_matrix
        instance._dist_coeff = dist_coeff
        instance._undistort_map1 = map1
        instance._undistort_map2 = map2
        instance._calibrated = True

        print(f"[INFO] Custom calibration loaded: fx={fx_real:.1f} fy={fy_real:.1f} "
              f"HFOV={hfov_real:.1f}° reproj_err={reproj_error:.4f}px")

        return instance

    # ── Undistort a frame ───────────────────────────────────────────────────
    def undistort(self, frame: np.ndarray) -> np.ndarray:
        """
        Sửa méo ống kính cho 1 frame.
        Nếu không có calibration data, trả về frame nguyên bản.
        """
        if not self._calibrated or self._undistort_map1 is None:
            return frame
        return cv2.remap(frame, self._undistort_map1, self._undistort_map2,
                         cv2.INTER_LINEAR)


# ─────────────────────────────────────────────────────────────────────────────
# Real-world vehicle widths (metres) used by the width-fallback distance
# estimator when the bbox foot is truncated at the bottom of the frame.
# Source: typical sedan / European bus / heavy truck mid-size.
# ─────────────────────────────────────────────────────────────────────────────
REAL_VEHICLE_WIDTHS_M = {
    0: 1.85,   # Car
    1: 2.55,   # Bus
    2: 2.55,   # Truck
}
DEFAULT_VEHICLE_WIDTH_M = 1.85

